# 01 Data Ingestion

## Purpose
Pull raw source data for the xwOBA pipeline and save it locally as parquet files.

## Inputs
- pybaseball Statcast API
- pybaseball sprint speed data
- local `wOBAbyYear.csv`

## Outputs
- `data/raw/statcast_events.parquet`
- `data/raw/sprint_speed.parquet`
- `data/raw/woba_weights.parquet`

In [1]:
import warnings
import pandas as pd
import os
import pybaseball as pb
from pybaseball.statcast_running import statcast_sprint_speed

In [2]:
warnings.filterwarnings("ignore")
pd.set_option("display.max_columns", 200)
pb.cache.enable()

SEASONS = [2023, 2024, 2025]
DATE_RANGES = {
    2023: ("2023-03-29", "2023-10-02"),
    2024: ("2024-03-27", "2024-09-30"),
    2025: ("2025-03-26", "2025-09-29"),
}

## Pull Statcast data

In [3]:
dfs = []

for y in SEASONS:
    start_dt, end_dt = DATE_RANGES[y]
    print(f"Pulling {y} data...")
    df_y = pb.statcast(start_dt=start_dt, end_dt=end_dt)
    df_y["season"] = y
    dfs.append(df_y)
    
raw_statcast = pd.concat(dfs, ignore_index=True)

print("\nDone.")
print("Shape:", raw_statcast.shape)
raw_statcast.head()

Pulling 2023 data...
This is a large query, it may take a moment to complete

100%|██████████| 188/188 [01:01<00:00,  3.05it/s]

Pulling 2024 data...
This is a large query, it may take a moment to complete

100%|██████████| 188/188 [01:08<00:00,  2.74it/s]

Pulling 2025 data...
This is a large query, it may take a moment to complete

100%|██████████| 188/188 [00:52<00:00,  3.56it/s]

Done.
Shape: (2143789, 119)

,pitch_type,game_date,release_speed,release_pos_x,release_pos_z,player_name,batter,pitcher,events,description,spin_dir,spin_rate_deprecated,break_angle_deprecated,break_length_deprecated,zone,des,game_type,stand,p_throws,home_team,away_team,type,hit_location,bb_type,balls,strikes,game_year,pfx_x,pfx_z,plate_x,plate_z,on_3b,on_2b,on_1b,outs_when_up,inning,inning_topbot,hc_x,hc_y,tfs_deprecated,tfs_zulu_deprecated,umpire,sv_id,vx0,vy0,vz0,ax,ay,az,sz_top,sz_bot,hit_distance_sc,launch_speed,launch_angle,effective_speed,release_spin_rate,release_extension,game_pk,fielder_2,fielder_3,fielder_4,fielder_5,fielder_6,fielder_7,fielder_8,fielder_9,release_pos_y,estimated_ba_using_speedangle,estimated_woba_using_speedangle,woba_value,woba_denom,babip_value,iso_value,launch_speed_angle,at_bat_number,pitch_number,pitch_name,home_score,away_score,bat_score,fld_score,post_away_score,post_home_score,post_bat_score,post_fld_score,if_fielding_alignment,of_fielding_alignment,spin_axis,delta_home_win_exp,delta_run_exp,bat_speed,swing_length,estimated_slg_using_speedangle,delta_pitcher_run_exp,hyper_speed,home_score_diff,bat_score_diff,home_win_exp,bat_win_exp,age_pit_legacy,age_bat_legacy,age_pit,age_bat,n_thruorder_pitcher,n_priorpa_thisgame_player_at_bat,pitcher_days_since_prev_game,batter_days_since_prev_game,pitcher_days_until_next_game,batter_days_until_next_game,api_break_z_with_gravity,api_break_x_arm,api_break_x_batter_in,arm_angle,attack_angle,attack_direction,swing_path_tilt,intercept_ball_minus_batter_pos_x_inches,intercept_ball_minus_batter_pos_y_inches,season
0,CH,2023-10-01,89.0,-2.8,5.59,"Robertson, Nick",677008,687798,field_out,hit_into_play,<NA>,<NA>,<NA>,<NA>,9,"Heston Kjerstad grounds out, first baseman Bob...",R,L,R,BAL,BOS,X,3,ground_ball,2,2,2023,-1.53,0.33,0.333018,2.005061,<NA>,<NA>,<NA>,2,9,Bot,158.28,166.83,<NA>,<NA>,<NA>,<NA>,11.122985,-129.176025,-3.49208,-19.471845,26.055263,-27.922064,3.81,1.74,6,96.4,-17,90.7,1703,7.4,716367,657136,666915,665839,622569,596115,677800,678882,608701,53.11,0.147,0.152,0.0,1,0,0,2,73,6,Changeup,1,6,1,6,6,1,1,6,Infield shade,Standard,250,-0.001,-0.233,66.5,6.5,0.149,0.233,96.4,-5,-5,0.001,0.001,24,24,25,24,1,3,11,1,<NA>,<NA>,2.55,1.53,-1.53,31.7,1.676715,-1.896554,41.830979,30.714944,26.41202,2023
1,FF,2023-10-01,96.9,-2.4,5.9,"Robertson, Nick",677008,687798,None,foul,<NA>,<NA>,<NA>,<NA>,5,Foul,R,L,R,BAL,BOS,S,<NA>,None,2,2,2023,-0.76,1.36,0.091181,2.705577,<NA>,<NA>,<NA>,2,9,Bot,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,8.558215,-140.741874,-6.148396,-12.116762,34.259201,-12.836434,3.81,1.74,223,78.2,56,98.4,2153,7.4,716367,657136,666915,665839,622569,596115,677800,678882,608701,53.13,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,73,5,4-Seam Fastball,1,6,1,6,6,1,1,6,Infield shade,Standard,211,0.0,0.0,70.8,6.7,<NA>,0.0,88.0,-5,-5,0.001,0.001,24,24,25,24,1,3,11,1,<NA>,<NA>,1.09,0.76,-0.76,47.4,8.715532,3.692542,40.551342,33.656454,26.020583,2023
2,CH,2023-10-01,90.0,-2.93,5.56,"Robertson, Nick",677008,687798,None,ball,<NA>,<NA>,<NA>,<NA>,13,Ball,R,L,R,BAL,BOS,B,<NA>,None,1,2,2023,-1.65,0.36,-0.24348,0.531787,<NA>,<NA>,<NA>,2,9,Bot,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,10.328033,-130.515462,-7.371558,-20.978432,27.339657,-26.599717,3.712182,1.775306,<NA>,<NA>,<NA>,91.5,1698,7.4,716367,657136,666915,665839,622569,596115,677800,678882,608701,53.14,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,73,4,Changeup,1,6,1,6,6,1,1,6,Infield shade,Standard,250,0.0,0.041,<NA>,<NA>,<NA>,-0.041,<NA>,-5,-5,0.001,0.001,24,24,25,24,1,3,11,1,<NA>,<NA>,2.47,1.65,-1.65,30.3,<NA>,<NA>,<NA>,<NA>,<NA>,2023
3,ST,2023-10-01,82.2,-3.09,5.55,"Robertson, Nick",677008,687798,None,ball,<NA>,<NA>,<NA>,<NA>,14,Ball,R,L,R,BAL,BOS,B,<NA>,None,0,2,2023,1.43,0.28,0.808145,0.486074,<NA>,<NA>,<NA>,2,9,Bot,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,6.108013,-119.483805,-5.435467,12.155221,26.646301,-28.491928,3.781975,1.739611,<NA>,<NA>,<NA>,82.4,2786,6.9,716367,657136,666915,665839,622569,596115,677800,678882,608701,53.63,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,73,3,Sweeper,1,6,1,6,6,1,1,6,Infield shade,Standard,58,0.0,0.022,<NA>,<NA>,<NA>,-0.022,<NA>,-5,-5,0.001,0.001,24,24,25,24,1,3,11,1,<NA>,<NA>,3.14,-1.43,1.43,28.9,<NA>,<NA>,<NA>,<NA>,<NA>,2023
4,CH,2023-10-01,89.2,-2.87,5.58,"Robertson, Nick",677008,687798,None,swinging_strike,<NA>,<NA>,<NA>,<NA>,7,Swinging Strike,R,L,R,BAL,BOS,S,<NA>,None,0,1,2023,-1.49,0.31,-0.781951,2.045985,<NA>,<NA>,<NA>,2,9,Bot,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,8.417443,-129.604641,-3.33637,-18.554455,27.650862,-28.148796,3.81,1.74,<NA>,<NA>,<NA>,90.5,1589,7.2,716367,657136,666915,665839,622569,596115,677800,678882,608701,53.29,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,73,2,Changeup,1,6,1,6,6,1,1,6,Infield shade,Standard,257,0.0,-0.061,77.9,7.8,<NA>,0.061,<NA>,-5,-5,0.001,0.001,24,24,25,24,1,3,11,1,<NA>,<NA>,2.57,1.49,-1.49,34.3,20.169759,-7.584644,37.675911,44.236969,36.187039,2023

In [4]:
raw_statcast.head(50)

,pitch_type,game_date,release_speed,release_pos_x,release_pos_z,player_name,batter,pitcher,events,description,spin_dir,spin_rate_deprecated,break_angle_deprecated,break_length_deprecated,zone,des,game_type,stand,p_throws,home_team,away_team,type,hit_location,bb_type,balls,strikes,game_year,pfx_x,pfx_z,plate_x,plate_z,on_3b,on_2b,on_1b,outs_when_up,inning,inning_topbot,hc_x,hc_y,tfs_deprecated,tfs_zulu_deprecated,umpire,sv_id,vx0,vy0,vz0,ax,ay,az,sz_top,sz_bot,hit_distance_sc,launch_speed,launch_angle,effective_speed,release_spin_rate,release_extension,game_pk,fielder_2,fielder_3,fielder_4,fielder_5,fielder_6,fielder_7,fielder_8,fielder_9,release_pos_y,estimated_ba_using_speedangle,estimated_woba_using_speedangle,woba_value,woba_denom,babip_value,iso_value,launch_speed_angle,at_bat_number,pitch_number,pitch_name,home_score,away_score,bat_score,fld_score,post_away_score,post_home_score,post_bat_score,post_fld_score,if_fielding_alignment,of_fielding_alignment,spin_axis,delta_home_win_exp,delta_run_exp,bat_speed,swing_length,estimated_slg_using_speedangle,delta_pitcher_run_exp,hyper_speed,home_score_diff,bat_score_diff,home_win_exp,bat_win_exp,age_pit_legacy,age_bat_legacy,age_pit,age_bat,n_thruorder_pitcher,n_priorpa_thisgame_player_at_bat,pitcher_days_since_prev_game,batter_days_since_prev_game,pitcher_days_until_next_game,batter_days_until_next_game,api_break_z_with_gravity,api_break_x_arm,api_break_x_batter_in,arm_angle,attack_angle,attack_direction,swing_path_tilt,intercept_ball_minus_batter_pos_x_inches,intercept_ball_minus_batter_pos_y_inches,season
0,CH,2023-10-01,89.0,-2.8,5.59,"Robertson, Nick",677008,687798,field_out,hit_into_play,<NA>,<NA>,<NA>,<NA>,9,"Heston Kjerstad grounds out, first baseman Bob...",R,L,R,BAL,BOS,X,3,ground_ball,2,2,2023,-1.53,0.33,0.333018,2.005061,<NA>,<NA>,<NA>,2,9,Bot,158.28,166.83,<NA>,<NA>,<NA>,<NA>,11.122985,-129.176025,-3.49208,-19.471845,26.055263,-27.922064,3.81,1.74,6,96.4,-17,90.7,1703,7.4,716367,657136,666915,665839,622569,596115,677800,678882,608701,53.11,0.147,0.152,0.0,1,0,0,2,73,6,Changeup,1,6,1,6,6,1,1,6,Infield shade,Standard,250,-0.001,-0.233,66.5,6.5,0.149,0.233,96.4,-5,-5,0.001,0.001,24,24,25,24,1,3,11,1,<NA>,<NA>,2.55,1.53,-1.53,31.7,1.676715,-1.896554,41.830979,30.714944,26.41202,2023
1,FF,2023-10-01,96.9,-2.4,5.9,"Robertson, Nick",677008,687798,None,foul,<NA>,<NA>,<NA>,<NA>,5,Foul,R,L,R,BAL,BOS,S,<NA>,None,2,2,2023,-0.76,1.36,0.091181,2.705577,<NA>,<NA>,<NA>,2,9,Bot,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,8.558215,-140.741874,-6.148396,-12.116762,34.259201,-12.836434,3.81,1.74,223,78.2,56,98.4,2153,7.4,716367,657136,666915,665839,622569,596115,677800,678882,608701,53.13,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,73,5,4-Seam Fastball,1,6,1,6,6,1,1,6,Infield shade,Standard,211,0.0,0.0,70.8,6.7,<NA>,0.0,88.0,-5,-5,0.001,0.001,24,24,25,24,1,3,11,1,<NA>,<NA>,1.09,0.76,-0.76,47.4,8.715532,3.692542,40.551342,33.656454,26.020583,2023
2,CH,2023-10-01,90.0,-2.93,5.56,"Robertson, Nick",677008,687798,None,ball,<NA>,<NA>,<NA>,<NA>,13,Ball,R,L,R,BAL,BOS,B,<NA>,None,1,2,2023,-1.65,0.36,-0.24348,0.531787,<NA>,<NA>,<NA>,2,9,Bot,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,10.328033,-130.515462,-7.371558,-20.978432,27.339657,-26.599717,3.712182,1.775306,<NA>,<NA>,<NA>,91.5,1698,7.4,716367,657136,666915,665839,622569,596115,677800,678882,608701,53.14,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,73,4,Changeup,1,6,1,6,6,1,1,6,Infield shade,Standard,250,0.0,0.041,<NA>,<NA>,<NA>,-0.041,<NA>,-5,-5,0.001,0.001,24,24,25,24,1,3,11,1,<NA>,<NA>,2.47,1.65,-1.65,30.3,<NA>,<NA>,<NA>,<NA>,<NA>,2023
3,ST,2023-10-01,82.2,-3.09,5.55,"Robertson, Nick",677008,687798,None,ball,<NA>,<NA>,<NA>,<NA>,14,Ball,R,L,R,BAL,BOS,B,<NA>,None,0,2,2023,1.43,0.28,0.808145,0.486074,<NA>,<NA>,<NA>,2,9,Bot,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,6.108013,-119.483805,-5.435467,12.155221,26.646301,-28.491928,3.781975,1.739611,<NA>,<NA>,<NA>,82.4,2786,6.9,716367,657136,666915,665839,622569,596115,677800,678882,608701,53.63,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,73,3,Sweeper,1,6,1,6,6,1,1,6,Infield shade,Standard,58,0.0,0.022,<NA>,<NA>,<NA>,-0.022,<NA>,-5,-5,0.001,0.001,24,24,25,24,1,3,11,1,<NA>,<NA>,3.14,-1.43,1.43,28.9,<NA>,<NA>,<NA>,<NA>,<NA>,2023
4,CH,2023-10-01,89.2,-2.87,5.58,"Robertson, Nick",677008,687798,None,swinging_strike,<NA>,<NA>,<NA>,<NA>,7,Swinging Strike,R,L,R,BAL,BOS,S,<NA>,None,0,1,2023,-1.49,0.31,-0.781951,2.045985,<NA>,<NA>,<NA>,2,9,Bot,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,8.417443,-129.604641,-3.33637,-18.554455,27.650862,-28.148796,3.81,1.74,<NA>,<NA>,<NA>,90.5,1589,7.2,716367,657136,666915,665839,622569,596115,677800,678882,608701,53.29,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,73,2,Changeup,1,6,1,6,6,1,1,6,Infield shade,Standard,257,0.0,-0.061,77.9,7.8,<NA>,0.061,<NA>,-5,-5,0.001,0.001,24,24,25,24,1,3,11,1,<NA>,<NA>,2.57,1.49,-1.49,34.3,20.169759,-7.584644,37.675911,44.236969,36.187039,2023
5,FF,2023-10-01,96.2,-2.37,5.96,"Robertson, Nick",677008,687798,None,swinging_strike,<NA>,<NA>,<NA>,<NA>,3,Swinging Strike,R,L,R,BAL,BOS,S,<NA>,None,0,0,2023,-0.71,1.4,0.587847,3.558311,<NA>,<NA>,<NA>,2,9,Bot,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,9.626067,-139.750857,-3.982147,-11.630817,33.893158,-13.112827,3.809705,1.739611,<NA>,<NA>,<NA>,97.4,2213,7.3,716367,657136,666915,665839,622569,596115,677800,678882,608701,53.24,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,73,1,4-Seam Fastball,1,6,1,6,6,1,1,6,Infield shade,Standard,215,0.0,-0.045,<NA>,<NA>,<NA>,0.045,<NA>,-5,-5,0.001,0.001,24,24,25,24,1,3,11,1,<NA>,<NA>,1.08,0.71,-0.71,43.8,<NA>,<NA>,<NA>,<NA>,<NA>,2023
6,CH,2023-10-01,88.2,-2.86,5.51,"Robertson, Nick",602104,687798,strikeout,swinging_strike,<NA>,<NA>,<NA>,<NA>,13,Ramon Urias strikes out swinging.,R,R,R,BAL,BOS,S,2,None,2,2,2023,-1.45,0.43,-0.815818,1.187745,<NA>,<NA>,<NA>,1,9,Bot,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,8.123411,-128.123445,-5.373029,-17.605529,26.545899,-26.498222,3.119666,1.459595,<NA>,<NA>,<NA>,89.6,1656,7.2,716367,657136,666915,665839,622569,596115,677800,678882,608701,53.26,<NA>,0.0,0.0,1,0,0,<NA>,72,6,Changeup,1,6,1,6,6,1,1,6,Standard,Standard,254,-0.002,-0.234,66.2,8.5,<NA>,0.234,<NA>,-5,-5,0.003,0.003,24,29,25,29,1,0,11,1,<NA>,6,2.51,1.45,1.45,31.8,12.675671,-25.318306,32.984103,29.051912,38.369551,2023
7,FF,2023-10-01,95.7,-2.4,5.8,"Robertson, Nick",602104,687798,None,foul,<NA>,<NA>,<NA>,<NA>,6,Foul,R,R,R,BAL,BOS,S,<NA>,None,2,2,2023,-0.48,1.3,0.502508,2.094303,<NA>,<NA>,<NA>,1,9,Bot,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,8.91699,-138.968451,-7.23025,-8.153688,30.274685,-13.803886,3.12,1.46,299,87.9,30,97.5,2097,7.4,716367,657136,666915,665839,622569,596115,677800,678882,608701,53.12,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,72,5,4-Seam Fastball,1,6,1,6,6,1,1,6,Standard,Standard,210,0.0,0.0,67.0,7.4,<NA>,0.0,88.0,-5,-5,0.003,0.003,24,29,25,29,1,0,11,1,<NA>,6,1.19,0.48,0.48,38.4,-3.690621,14.173457,27.01586,46.463475,19.285215,2023
8,ST,2023-10-01,79.4,-2.96,5.67,"Robertson, Nick",602104,687798,None,ball,<NA>,<NA>,<NA>,<NA>,11,Ball,R,R,R,BAL,BOS,B,<NA>,None,1,2,2023,1.66,-0.2,-1.844177,4.081095,<NA>,<NA>,<NA>,1,9,Bot,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,-0.672901,-115.511662,3.704152,15.019966,21.584765,-34.899383,3.071776,1.506613,<NA>,<NA>,<NA>,79.9,2744,6.6,716367,657136,666915,665839,622569,596115,677800,678882,608701,53.85,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,72,4,Sweeper,1,6,1,6,6,1,1,6,Standard,Standard,60,0.0,0.045,<NA>,<NA>,<NA>,-0.045,<NA>,-5,-5,0.003,0.003,24,29,25,29,1,0,11,1,<NA>,6,3.82,-1.66,-1.66,32.4,<NA>,<NA>,<NA>,<NA>,<NA>,2023
9,ST,2023-10-01,82.9,-2.82,5.66,"Robertson, Nick",602104,687798,None,ball,<NA>,<NA>,<NA>,<NA>,14,Ball,R,R,R,BAL,BOS,B,<NA>,None,0,2,2023,1.16,0.01,1.125976,0.970035,<NA>,<NA>,<NA>,1,9,Bot,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,6.837709,-120.679821,-4.33055,10.10397,22.062598,-31.4879,3.09508,1.459879,<NA>,<NA>,<NA>,84.1,2754,6.9,716367,657136,666915,665839,622569,596115,677800,678882,608701,53.57,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,72,3,Sweeper,1,6,1,6,6,1,1,6,Standard,Standard,62,0.001,0.019,<NA>,<NA>,<NA>,-0.019,<NA>,-5,-5,0.002,0.002,24,29,25,29,1,0,11,1,<NA>,6,3.29,-1.16,-1.16,32.8,<NA>,<NA>,<NA>,<NA>,<NA>,2023
10,ST,2023-10-01,82.0,-3.0,5.69,"Robertson, Nick",602104,687798,None,called_strike,<NA>,<NA>,<NA>,<NA>,4,Called Strike,R,R,R,BAL,BOS,S,<NA>,None,0,1,2023,1.45,0.06,-0.646679,2.34434,<NA>,<NA>,<NA>,1,9,Bot,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,2.512905,-119.426935,-1.117788,13.372972,23.916332,-31.571593,3.071776,1.483246,<NA>,<NA>,<NA>,82.4,2798,6.6,716367,657136,666915,665839,622569,596115,677800,678882,608701,53.93,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,72,2,Sweeper,1,6,1,6,6,1,1,6,Standard,Standard,63,-0.001,-0.057,<NA>,<NA>,<NA>,0.057,<NA>,-5,-5,0.003,0.003,24,29,25,29,1,0,11,1,<NA>,6,3.33,-1.45,-1.45,32.7,<NA>,<NA>,<NA>,<NA>,<NA>,2023
11,FF,2023-10-01,97.0,-2.33,6.0,"Robertson, Nick",602104,687798,None,foul_tip,<NA>,<NA>,<NA>,<NA>,11,Foul Tip,R,R,R,BAL,BOS,S,<NA>,None,0,0,2023,-0.63,1.27,-0.086116,3.429748,<NA>,<NA>,<NA>,1,9,Bot,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,7.596831,-141.102552,-4.335451,-10.160724,31.850014,-14.337009,3.119621,1.459538,<NA>,<NA>,<NA>,98.8,2207,7.3,716367,657136,666915,665839,622569,596115,677800,678882,608701,53.23,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,72,1,4-Seam Fastball,1,6,1,6,6,1,1,6,Standard,Standard,209,0.0,-0.041,73.4,7.2,<NA>,0.041,<NA>,-5,-5,0.003,0.003,24,29,25,29,1,0,11,1,<NA>,6,1.15,0.63,0.63,41.2,13.289219,13.438837,19.055932,37.89498,24.971032,2023
12,FF,2023-10-01,95.8,-2.48,5.88,"Robertson, Nick",663624,687798,field_out,hit_into_play,<NA>,<NA>,<NA>,<NA>,13,Ryan Mountcastle pops out to second baseman En...,R,R,R,BAL,BOS,X,4,popup,3,1,2023,-0.54,1.58,-1.051937,2.766499,<NA>,<NA>,<NA>,0,9,Bot,168.39,135.05,<NA>,<NA>,<NA>,<NA>,5.071337,-139.246921,-6.233062,-8.158237,33.874278,-10.472415,3.73,1.86,194,68.3,46,97.3,2204,7.4,716367,657136,666915,665839,622569,596115,677800,678882,608701,53.13,0.284,0.293,0.0,1,0,0,3,71,5,4-Seam Fastball,1,6,1,6,6,1,1,6,Standard,Standard,212,-0.009,-0.442,69.3,6.4,0.387,0.442,88.0,-5,-5,0.012,0.012,24,26,25,26,1,1,11,1,<NA>,6,0.93,0.54,0.54,42.9,-4.578371,1.280243,40.060882,24.734672,25.749552,2023
13,FF,2023-10-01,96.0,-2.44,5.94,"Robertson, Nick",663624,687798,None,ball,<NA>,<NA>,<NA>,<NA>,14,Ball,R,R,R,BAL,BOS,B,<NA>,None,2,1,2023,-0.33,1.45,1.141662,1.713738,<NA>,<NA>,<NA>,0,9,Bot,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,10.415362,-139.186629,-8.968103,-6.760695,32.907439,-11.41145,3.67724,1.859564,<NA>,<NA>,<NA>,97.4,2229,7.4,716367,657136,666915,665839,622569,596115,677800,678882,608701,53.09,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,71,4,4-Seam Fastball,1,6,1,6,6,1,1,6,Standard,Standard,208,0.003,0.129,<NA>,<NA>,<NA>,-0.129,<NA>,-5,-5,0.009,0.009,24,26,25,26,1,1,11,1,<NA>,6,1.05,0.33,0.33,41.7,<NA>,<NA>,<NA>,<NA>,<NA>,2023
14,FF,2023-10-01,96.1,-2.37,5.94,"Robertson, Nick",663624,687798,None,ball,<NA>,<NA>,<NA>,<NA>,9,Ball,R,R,R,BAL,BOS,B,<NA>,None,1,1,2023,-0.45,1.52,0.750947,1.963383,<NA>,<NA>,<NA>,0,9,Bot,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,9.411136,-139.426915,-8.486051,-8.031747,31.91236,-10.500938,3.676897,1.66971,<NA>,<NA>,<NA>,97.3,2224,7.2,716367,657136,666915,665839,622569,596115,677800,678882,608701,53.35,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,71,3,4-Seam Fastball,1,6,1,6,6,1,1,6,Standard,Standard,213,0.001,0.059,<NA>,<NA>,<NA>,-0.059,<NA>,-5,-5,0.008,0.008,24,26,25,26,1,1,11,1,<NA>,6,0.96,0.45,0.45,42.6,<NA>,<NA>,<NA>,<NA>,<NA>,2023
15,FF,2023-10-01,97.3,-2.31,6.07,"Robertson, Nick",663624,687798,None,foul,<NA>,<NA>,<NA>,<NA>,5,Foul,R,R,R,BAL,BOS,S,<NA>,None,1,0,2023,-0.62,1.24,-0.119164,3.070976,<NA>,<NA>,<NA>,0,9,Bot,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,7.417688,-141.504377,-5.44697,-9.962494,32.03823,-14.41825,3.73,1.86,13,95.9,-12,98.8,2121,7.1,716367,657136,666915,665839,622569,596115,677800,678882,608701,53.36,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,71,2,4-Seam Fastball,1,6,1,6,6,1,1,6,Standard,Standard,212,-0.001,-0.052,65.4,5.3,<NA>,0.052,95.9,-5,-5,0.009,0.009,24,26,25,26,1,1,11,1,<NA>,6,1.17,0.62,0.62,40.8,-26.558038,53.444636,40.553326,37.151996,-2.907958,2023
16,FF,2023-10-01,96.7,-2.47,5.89,"Robertson, Nick",663624,687798,None,ball,<NA>,<NA>,<NA>,<NA>,13,Ball,R,R,R,BAL,BOS,B,<NA>,None,0,0,2023,-0.82,1.14,-0.343395,1.29234,<NA>,<NA>,<NA>,0,9,Bot,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,7.68233,-140.411925,-9.442643,-12.645057,32.275418,-15.062438,3.729661,1.868656,<NA>,<NA>,<NA>,98.3,1961,7.3,716367,657136,666915,665839,622569,596115,677800,678882,608701,53.18,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,71,1,4-Seam Fastball,1,6,1,6,6,1,1,6,Standard,Standard,213,0.001,0.04,<NA>,<NA>,<NA>,-0.04,<NA>,-5,-5,0.008,0.008,24,26,25,26,1,1,11,1,<NA>,6,1.31,0.82,0.82,38.8,<NA>,<NA>,<NA>,<NA>,<NA>,2023
17,SI,2023-10-01,93.7,1.04,6.37,"Irvin, Cole",678882,608344,strikeout,called_strike,<NA>,<NA>,<NA>,<NA>,1,Ceddanne Rafaela called out on strikes.,R,R,L,BAL,BOS,S,2,None,2,2,2023,1.23,0.85,-0.671859,3.063874,<NA>,<NA>,<NA>,2,9,Top,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,-7.150373,-136.364352,-4.776267,16.888987,26.39233,-20.642613,3.362894,1.611637,<NA>,<NA>,<NA>,94.2,1955,6.3,716367,543510,663624,676059,602104,683002,677008,622761,623993,54.16,<NA>,0.0,0.0,1,0,0,<NA>,70,5,Sinker,1,6,6,1,6,1,6,1,Standard,Standard,142,0.0,-0.233,<NA>,<NA>,<NA>,0.233,<NA>,-5,5,0.008,0.992,29,22,29,23,1,1,19,1,<NA>,<NA>,1.72,1.23,-1.23,47.6,<NA>,<NA>,<NA>,<NA>,<NA>,2023
18,FC,2023-10-01,82.7,1.35,6.17,"Irvin, Cole",678882,608344,None,swinging_strike,<NA>,<NA>,<NA>,<NA>,7,Swinging Strike,R,R,L,BAL,BOS,S,<NA>,None,2,1,2023,-0.21,0.1,-0.818244,1.702825,<NA>,<NA>,<NA>,2,9,Top,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,-4.552219,-120.455004,-3.961904,-1.242669,21.410101,-30.683167,3.29,1.54,<NA>,<NA>,<NA>,83.3,2196,6.4,716367,543510,663624,676059,602104,683002,677008,622761,623993,54.07,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,70,4,Cutter,1,6,6,1,6,1,6,1,Standard,Standard,264,0.0,-0.081,63.9,8.8,<NA>,0.081,<NA>,-5,5,0.008,0.992,29,22,29,23,1,1,19,1,<NA>,<NA>,3.2,-0.21,0.21,41.4,25.632681,-41.943644,37.117458,27.100561,52.045163,2023
19,FC,2023-10-01,85.2,1.46,6.21,"Irvin, Cole",678882,608344,None,ball,<NA>,<NA>,<NA>,<NA>,12,Ball,R,R,L,BAL,BOS,B,<NA>,None,1,1,2023,-0.2,0.29,1.713683,2.65524,<NA>,<NA>,<NA>,2,9,Top,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,0.994746,-124.227006,-2.709328,-2.232603,22.150204,-28.887768,3.26973,1.588275,<NA>,<NA>,<NA>,85.5,2065,6.2,716367,543510,663624,676059,602104,683002,677008,622761,623993,54.34,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,70,3,Cutter,1,6,6,1,6,1,6,1,Standard,Standard,176,0.0,0.053,<NA>,<NA>,<NA>,-0.053,<NA>,-5,5,0.008,0.992,29,22,29,23,1,1,19,1,<NA>,<NA>,2.81,-0.2,0.2,38.6,<NA>,<NA>,<NA>,<NA>,<NA>,2023
20,CH,2023-10-01,84.5,1.43,6.12,"Irvin, Cole",678882,608344,None,swinging_strike,<NA>,<NA>,<NA>,<NA>,14,Swinging Strike,R,R,L,BAL,BOS,S,<NA>,None,1,0,2023,1.04,0.42,0.934865,1.760131,<NA>,<NA>,<NA>,2,9,Top,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,-3.2357,-123.108301,-4.707736,11.282312,22.238916,-27.225563,3.29,1.54,<NA>,<NA>,<NA>,85.0,1543,6.3,716367,543510,663624,676059,602104,683002,677008,622761,623993,54.17,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,70,2,Changeup,1,6,6,1,6,1,6,1,Standard,Standard,125,0.0,-0.056,64.6,8.5,<NA>,0.056,<NA>,-5,5,0.008,0.992,29,22,29,23,1,1,19,1,<NA>,<NA>,2.74,1.04,-1.04,37.8,22.574516,-17.666814,32.715559,47.440807,42.033492,2023
21,CU,2023-10-01,75.9,1.36,6.35,"Irvin, Cole",678882,608344,None,ball,<NA>,<NA>,<NA>,<NA>,14,Ball,R,R,L,BAL,BOS,B,<NA>,None,0,0,2023,-0.42,-0.64,1.068683,2.074735,<NA>,<NA>,<NA>,2,9,Top,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,0.12955,-110.663557,-0.827886,-3.461116,17.912793,-37.490391,3.246435,1.539428,<NA>,<NA>,<NA>,76.0,2210,6.0,716367,543510,663624,676059,602104,683002,677008,622761,623993,54.48,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,70,1,Curveball,1,6,6,1,6,1,6,1,Standard,Standard,324,0.0,0.043,<NA>,<NA>,<NA>,-0.043,<NA>,-5,5,0.008,0.992,29,22,29,23,1,1,19,1,<NA>,<NA>,4.55,-0.42,0.42,44.0,<NA>,<NA>,<NA>,<NA>,<NA>,2023
22,FC,2023-10-01,83.6,1.42,6.13,"Irvin, Cole",624512,608344,field_out,hit_into_play,<NA>,<NA>,<NA>,<NA>,13,"Reese McGuire grounds out, pitcher Cole Irvin ...",R,L,L,BAL,BOS,X,1,ground_ball,0,2,2023,-0.06,-0.17,-0.912408,2.294593,<NA>,<NA>,<NA>,1,9,Top,127.46,186.95,<NA>,<NA>,<NA>,<NA>,-5.249558,-121.736232,-2.093667,0.459916,24.107616,-33.636595,3.42,1.7,1,62.6,-64,83.5,2273,6.2,716367,543510,663624,676059,602104,683002,677008,622761,623993,54.27,0.205,0.183,0.0,1,0,0,2,69,4,Cutter,1,6,6,1,6,1,6,1,Standard,Standard,284,0.001,-0.17,61.8,7.6,0.205,0.17,88.0,-5,5,0.007,0.993,29,28,29,28,1,1,19,1,<NA>,<NA>,3.43,-0.06,-0.06,39.2,0.237634,20.464121,24.866288,47.255717,20.158185,2023
23,SI,2023-10-01,91.4,1.12,6.33,"Irvin, Cole",624512,608344,None,foul,<NA>,<NA>,<NA>,<NA>,4,Foul,R,L,L,BAL,BOS,S,<NA>,None,0,2,2023,1.18,0.97,-0.457378,2.575618,<NA>,<NA>,<NA>,1,9,Top,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,-6.497555,-132.897595,-5.664997,15.359002,28.158637,-19.651273,3.42,1.7,250,79.5,33,91.4,1992,6.3,716367,543510,663624,676059,602104,683002,677008,622761,623993,54.21,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,69,3,Sinker,1,6,6,1,6,1,6,1,Standard,Standard,142,0.0,0.0,67.3,7.3,<NA>,0.0,88.0,-5,5,0.007,0.993,29,28,29,28,1,1,19,1,<NA>,<NA>,1.76,1.18,1.18,46.5,-8.820704,25.90632,31.440088,41.560957,10.099674,2023
24,CH,2023-10-01,83.3,1.29,6.18,"Irvin, Cole",624512,608344,None,swinging_strike,<NA>,<NA>,<NA>,<NA>,13,Swinging Strike,R,L,L,BAL,BOS,S,<NA>,None,0,1,2023,1.01,0.83,-0.229247,1.406526,<NA>,<NA>,<NA>,1,9,Top,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,-5.474182,-121.17498,-6.190198,11.016729,22.393579,-22.98743,3.42,1.7,<NA>,<NA>,<NA>,83.7,1451,6.4,716367,543510,663624,676059,602104,683002,677008,622761,623993,54.07,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,69,2,Changeup,1,6,6,1,6,1,6,1,Standard,Standard,133,0.0,-0.057,70.0,9.5,<NA>,0.057,<NA>,-5,5,0.007,0.993,29,28,29,28,1,1,19,1,<NA>,<NA>,2.44,1.01,1.01,42.4,26.059652,-30.471009,32.603196,41.365472,50.144536,2023
25,FC,2023-10-01,84.3,1.48,6.15,"Irvin, Cole",624512,608344,None,foul,<NA>,<NA>,<NA>,<NA>,13,Foul,R,L,L,BAL,BOS,S,<NA>,None,0,0,2023,-0.39,0.54,-0.944696,2.247667,<NA>,<NA>,<NA>,1,9,Top,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,-4.87813,-122.670449,-3.779416,-2.980604,23.869801,-26.196794,3.42,1.7,91,67.3,9,84.5,2141,6.4,716367,543510,663624,676059,602104,683002,677008,622761,623993,54.11,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,69,1,Cutter,1,6,6,1,6,1,6,1,Standard,Standard,184,0.0,-0.041,64.0,8.9,<NA>,0.041,88.0,-5,5,0.007,0.993,29,28,29,28,1,1,19,1,<NA>,<NA>,2.66,-0.39,-0.39,39.0,11.650228,-14.106055,28.661494,49.474255,35.878964,2023
26,SI,2023-10-01,89.3,1.14,6.33,"Irvin, Cole",622569,608344,field_out,hit_into_play,<NA>,<NA>,<NA>,<NA>,1,Pablo Reyes grounds out to first baseman Ryan ...,R,R,L,BAL,BOS,X,3,ground_ball,0,2,2023,1.28,0.96,-0.297831,3.19833,<NA>,<NA>,<NA>,0,9,Top,153.72,172.92,<NA>,<NA>,<NA>,<NA>,-6.249503,-129.945518,-3.724564,15.822763,27.24765,-20.677397,3.36,1.62,4,80.5,-38,89.3,1907,6.3,716367,543510,663624,676059,602104,683002,677008,622761,623993,54.19,0.061,0.06,0.0,1,0,0,2,68,3,Sinker,1,6,6,1,6,1,6,1,Standard,Standard,141,0.001,-0.169,52.3,4.8,0.066,0.169,88.0,-5,5,0.006,0.994,29,29,29,30,1,2,19,1,<NA>,<NA>,1.9,1.28,-1.28,41.6,-14.475611,36.964367,32.074921,31.026654,10.562351,2023
27,CH,2023-10-01,82.5,1.36,6.18,"Irvin, Cole",622569,608344,None,foul,<NA>,<NA>,<NA>,<NA>,9,Foul,R,R,L,BAL,BOS,S,<NA>,None,0,1,2023,1.03,0.39,0.345982,1.639542,<NA>,<NA>,<NA>,0,9,Top,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,-4.304616,-120.150332,-4.60533,10.792103,22.664313,-27.762382,3.36,1.62,4,70.3,-24,82.7,1374,6.3,716367,543510,663624,676059,602104,683002,677008,622761,623993,54.15,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,68,2,Changeup,1,6,6,1,6,1,6,1,Standard,Standard,125,0.0,-0.054,68.0,8.2,<NA>,0.054,88.0,-5,5,0.006,0.994,29,29,29,30,1,2,19,1,<NA>,<NA>,2.95,1.03,-1.03,39.9,13.942991,-20.872708,29.714618,41.493882,41.425303,2023

## Pull sprint speed data

In [5]:
ss = pd.concat(
    [statcast_sprint_speed(y, min_opp=10).assign(season=y) for y in SEASONS],
    ignore_index=True
)

print("Sprint speed shape:", ss.shape)
ss.head()

Sprint speed shape: (1728, 11)

,"last_name, first_name",player_id,team_id,team,position,age,competitive_runs,bolts,hp_to_1b,sprint_speed,season
0,"De La Cruz, Elly",682829,113,CIN,SS,21,162,84.0,4.13,30.5,2023
1,"Witt Jr., Bobby",677951,118,KC,SS,23,262,149.0,4.12,30.5,2023
2,"Blanco, Dairon",680118,118,KC,RF,30,55,31.0,4.15,30.3,2023
3,"Turner, Trea",607208,143,PHI,SS,30,288,115.0,4.14,30.3,2023
4,"Thompson, Bubba",669352,140,TEX,LF,25,28,19.0,4.23,30.2,2023

## Load wOBA weights

In [6]:
woba = pd.read_csv("wOBAbyYear.csv")
woba = woba.rename(columns={
    "Season": "season",
    "wBB": "unintentional_bb",
    "wHBP": "hbp",
    "w1B": "single_weight",
    "w2B": "double_weight",
    "w3B": "triple_weight",
    "wHR": "hr_weight"
})
woba = woba[[
    "season",
    "unintentional_bb",
    "hbp",
    "single_weight",
    "double_weight",
    "triple_weight",
    "hr_weight"
]].copy()
woba["season"] = pd.to_numeric(woba["season"], errors="coerce").astype("Int64")
for col in [
    "unintentional_bb",
    "hbp",
    "single_weight",
    "double_weight",
    "triple_weight",
    "hr_weight"
]: woba[col] = pd.to_numeric(woba[col], errors="coerce")

woba = woba[woba["season"].isin(SEASONS)].copy()
woba = woba.sort_values("season").reset_index(drop=True)

print("wOBA weights shape:", woba.shape)
display(woba)

wOBA weights shape: (3, 7)

,season,unintentional_bb,hbp,single_weight,double_weight,triple_weight,hr_weight
0,2023,0.696,0.726,0.883,1.244,1.569,2.004
1,2024,0.689,0.720,0.882,1.254,1.590,2.050
2,2025,0.691,0.722,0.882,1.252,1.584,2.037

## Save raw datasets locally

In [7]:
os.makedirs("data/raw", exist_ok=True)

raw_statcast.to_parquet("data/raw/statcast_events.parquet", index=False)
ss.to_parquet("data/raw/sprint_speed.parquet", index=False)
woba.to_parquet("data/raw/woba_weights.parquet", index=False)

print("All raw datasets saved.")

All raw datasets saved.